cart/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add')
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from order.apis import OrderItemApi, OrderItemDetailApi
from order.views import OrderItemDetailView, OrderView, CustomerOrder
from product.views import *
from customer.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('product/', include('product.urls'), name='product'),
    path('accounts/', include('customer.urls', namespace='accounts')),
    path('order/<int:pk>', OrderItemApi.as_view()),
    path('cart/', OrderItemDetailView.as_view(), name='cart'),
    path('orderitem/<int:pk>', OrderItemDetailApi.as_view(), name='order_item'),
    path('rosetta/', include('rosetta.urls')),
    path('update_item/', updateItem, name='update_item'),
    path('address/', UserAddress.as_view(), name='address'),
    path('order/', OrderView.as_view(), name='order'),
    path('orders/', CustomerOrder.as_view(), name='orders')

]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'
urlpatterns = (
    path('', views.home, name='product'),
    path('product/<str:slug>/', views.home, name='category'),
    path('<str:slug>/', views.product_detail, name='product_detail'),
)

product/models.py
from django.db import models
from core.models import BaseModel
from django.utils.text import slugify
from django.urls import reverse


class Discount(BaseModel):
    value = models.PositiveIntegerField(null=False)
    type = models.CharField(max_length=10, choices=[('price', 'Price'), ('percent', 'Percent')], null=False)
    max_price = models.PositiveIntegerField(null=True, blank=True)

    def profit_value(self, price: int):
        """
        Calculate and Return the profit of the discount
        :param price: int (item value)
        :return: profit
        """
        if self.type == 'price':
            return min(self.value, price)
        else:  # percent
            raw_profit = int((self.value / 100) * price)
            return int(min(raw_profit, int(self.max_price))) if self.max_price else raw_profit


class Category(BaseModel):
    name = models.CharField(max_length=20)
    category_id = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='scategory')
    is_sub = models.BooleanField(default=False)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     super().save(*args, **kwargs)
    #
    # def get_absolute_url(self):
    #     return reverse('product:category_filter ', args=[self.slug, ])


class Product(BaseModel):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=4)
    category = models.ManyToManyField(Category, related_name='products')
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)
    discount_id = models.ForeignKey(Discount, on_delete=models.CASCADE, related_name='products', null=True, blank=True)
    brand = models.CharField(max_length=40)
    inventory = models.CharField(max_length=30)
    image = models.ImageField(upload_to='static/img')
    description = models.TextField()
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.name)
    #     super().save(*args, **kwargs)

    # def get_absolute_url(self):
    #     return reverse('product:product_detail', args=[self.slug, ])

product/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from order.models import Order, OrderItem
from .models import Product, Category
import json


def home(request, slug=None):
    product = Product.objects.filter(available=True)
    categories = Category.objects.filter(is_sub=False)
    if slug:
        category = get_object_or_404(Category, slug=slug)
        product = product.filter(category=category)
    return render(request, 'product/product.html', {'product': product, 'categories': categories})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    return render(request, 'product/product_detail.html', {'product': product})


def updateItem(request):
    data = json.loads(request.body)
    user = data['user']
    if user == 'AnonymousUser':
        messages.success(request, '.برای ثبت سفارش ابتدا باید وارد اکانتت خود شوید', 'warning')
    else:
        customer = request.user
        print(customer)
        productID = data['productID']
        # action = data['action']
        product = Product.objects.get(id=productID)

        # order, created = Order.objects.get_or_create(customer_id=customer)
        order = Order.objects.create(customer_id=customer)

        OrderItem.objects.get_or_create(order_id=order, product=product, customer_id=customer)
    return JsonResponse('Item was added', safe=False)

templates/product/product.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/product.css' %}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="sweetalert2.min.js"></script>
    <link rel="stylesheet" href="sweetalert2.min.css">
{% endblock %}
{% block body %}
    <div class="row">
        <div class="container">
            {% for category in categories %}
                <!-- Example split danger button -->
                <div class="btn-group">
                    <a href="{% url 'product:category' slug=category.slug %}"
                       class="btn btn-danger">{{ category.name }}</a>
                    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split"
                            data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                    </button>
                    <div class="dropdown-menu">
                        {% for i in category.scategory.all %}
                            <a class="dropdown-item" href="{% url 'product:category' slug=i.slug %}">{{ i.name }}</a>
                        {% endfor %}
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
    <br><br><br>
    <div class="row">
        <div class="container">
            {% for product in product %}
                <div class="card" style="width: 18rem;display: inline-block ; margin: 1rem">
                    <img class="card-img-top" src="{{ product.image.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <a href="{% url 'product:product_detail' slug=product.slug %}"
                           class="">{{ product.name }}</a>
                    </div>
                    <input data-action="add" data-product={{ product.id }}  type="submit" class="cart-btn update-cart"
                           value="افزودن به سبد خرید" style="width: 18rem;" id="button">
                </div>

            {% endfor %}
        </div>
    </div>
    <script>
        $('#button').click(function () {
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'محصول به سبد خرید اضافه شد',
                showConfirmButton: false,
                timer: 1500
            })
        })
    </script>
{% endblock %}

templates/product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/product.css' %}">
{% endblock %}
{% block body %}
    <main class="container">

        <!-- Left Column / Headphones Image -->
        <div class="">
            <img src="{{ product.image.url }}" alt="" width="400px" height="400px">
        </div>


        <!-- Right Column -->
        <div class="right-column">

            <!-- Product Description -->
            <div class="product-description">
                <h4>{{ product.brand }}</h4>
                <h1>{{ product.name }}</h1>
                <hr>
                <p>{{ product.description }}</p>
            </div>
            <!-- Product Pricing -->
            <div class="product-price">
                <span>تومان {{ product.price }}</span>
            </div>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
            </form>
        </div>
    </main>
{% endblock %}