cart/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add')
]

customer/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegistrView.as_view(), name='user_register'),
    path('verify/', views.UserRegistrVerifyCodeView.as_view(), name='verify_code'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from order.apis import OrderItemApi, OrderItemDetailApi
from order.views import OrderItemDetailView, OrderView, CustomerOrder
from product.views import *
from customer.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'), name='home'),
    path('product/', include('product.urls'), name='product'),
    path('accounts/', include('customer.urls', namespace='accounts')),
    path('order/<int:pk>', OrderItemApi.as_view()),
    path('cart/', OrderItemDetailView.as_view(), name='cart'),
    path('orderitem/<int:pk>', OrderItemDetailApi.as_view(), name='order_item'),
    path('rosetta/', include('rosetta.urls')),
    path('update_item/', updateItem, name='update_item'),
    path('address/', UserAddress.as_view(), name='address'),
    path('order/', OrderView.as_view(), name='order'),
    path('orders/', CustomerOrder.as_view(), name='orders')

]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'product'
urlpatterns = (
    path('', views.home, name='product'),
    path('product/<str:slug>/', views.home, name='category'),
    path('<str:slug>/', views.product_detail, name='product_detail'),
)

templates/inc/fotter.html
{% load static %}
<section class="footer">
    <div class="box-container">

        <div class="box">
            <h3>دیگر شعبه ها</h3>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> تهران </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> مشهد </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> اصفهان </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> شیراز </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> تبریز </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i> یزد </a>
            <a href="#"> <i class="fas fa-map-marker-alt"></i>همدان </a>

        </div>

        <div class="box">
            <h3>quick links</h3>
            <a href="#"> <i class="fas fa-arrow-right"></i> خانه </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> ویژه </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> برجسته </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> نظرات </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> وبلاگ </a>
        </div>

        <div class="box">
            <h3>extra links</h3>
            <a href="#"> <i class="fas fa-arrow-right"></i> حساب کاربری </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> اقلام سفارش داده شده </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> قوانین </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> روش پرداخت </a>
            <a href="#"> <i class="fas fa-arrow-right"></i> دیگر سرویس ها </a>
        </div>

        <div class="box">
            <h3>contact info</h3>
            <a href="#"> <i class="fas fa-phone"></i> +98-9305251819 </a>
            <a href="#"> <i class="fas fa-phone"></i> +98-9184999263 </a>
            <a href="#"> <i class="fas fa-envelope"></i> mahdizolfaghari3181@gmail.com </a>
            <img src="{% static 'img/worldmap.png' %}" class="map" alt="">
        </div>

    </div>

    <div class="share">
        <a href="#" class="fab fa-facebook-f"></a>
        <a href="#" class="fab fa-twitter"></a>
        <a href="#" class="fab fa-instagram"></a>
        <a href="#" class="fab fa-linkedin"></a>
        <a href="#" class="fab fa-pinterest"></a>
    </div>
</section>

<!-- footer section ends -->

<!-- loader  -->

<div class="loader-container">
    <img src="../../static/img/loader-img.gif" alt="">
</div>

templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}" style="padding: 2rem ;margin-top: 2rem">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<header class="header">

    <div class="header-1">

        <a href="#" class="logo"> <i class="fas fa-book"></i> کتابخانه </a>

        <form action="" class="search-form">
            <input type="search" name="" placeholder="جستجو کنید" id="search-box">
            <label for="search-box" class="fas fa-search"></label>
        </form>

        <div class="icons">
            <div id="search-btn" class="fas fa-search">
            </div>
            <a href="#" class="fas fa-heart"></a>
            <a href="{% url 'cart' %}" class="fas fa-shopping-cart"></a>
            {% if request.user.is_authenticated %}
                <div id="login-btn" class="fas fa-user"></div>
            {% else %}
                <div id="login-btn"></div>
            {% endif %}
        </div>
    </div>
    <div class="header-2">
        <nav class="navbar" style="justify-content: center">
            <a href="{% url 'home:home' %}">خانه</a>
            <a href="{% url 'product:product' %}">محصولات</a>
            <a href="#arrivals">ویژه</a>
            <a href="#reviews">نظرات</a>
            <a href="#blogs">وبلاگ</a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}">خروج</a>
            {% else %}
                <a href="{% url 'accounts:login' %}">ورود</a>
                <a href="{% url 'accounts:user_register' %}">ثبت نام</a>
            {% endif %}
        </nav>
    </div>
    <nav class=" bottom-navbar">
        <a href="{% url 'home:home' %}" class="fas fa-home"></a>
        <a href="{% url 'product:product' %}" class="fas fa-list"></a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}" class="fas fa-logout"></a>
        {% else %}
            <a href="{% url 'accounts:login' %}" class="fas fa-sign-in"></a>
            <a href="{% url 'accounts:user_register' %}" class="fas fa-sign-out"></a>
        {% endif %}
        <a href="#arrivals" class="fas fa-tags"></a>
        <a href="#reviews" class="fas fa-comments"></a>
        <a href="#blogs" class="fas fa-blog"></a>
    </nav>
    <div class="login-form-container">
        <div id="close-login-btn" class="fas fa-times"></div>
        <div class="">
            <h3 style="text-align: end;">:مدریت حساب</h3>
            <hr>
            {% if request.user.is_authenticated %}
                <button class="btn btn-primary form-control" style="width: 28rem;
">
                    <a href="{% url 'address' %}" style="color: white">ثبت آدرس جدید</a>
                </button>
                <button class="btn btn-primary form-control" style="width: 28rem;
">
                    <a href="{% url 'orders' %}" style="color: white">سفارش ها</a>
                </button>
            {% else %}
                <p>.ابتدا وارد حساب خود شوید</p>
            {% endif %}

        </div>

    </div>
</header>